# Generated by Django 5.0.2 on 2025-05-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_songlike'),
        ('playlist', '0002_alter_playlist_options_rename_user_playlist_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongVector',
            fields=[
                ('song', models.OneToOneField(help_text='FK to music_song', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vector', serialize=False, to='music.song')),
                ('cf_vector', models.JSONField(default=list, help_text='Model-based CF 向量')),
                ('content_vector', models.JSONField(default=list, help_text='CB One-Hot 向量')),
                ('hybrid_vector', models.JSONField(default=list, help_text='拼接向量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'song_vectors',
            },
        ),
    ]
