# Generated by Django 5.0.2 on 2025-05-13 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playlist", "0003_songvector"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SongVector",
        ),
    ]
