# Generated by Django 5.0.2 on 2025-05-13 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0003_songlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongVector',
            fields=[
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='music.song')),
                ('cf_vector', models.JSONField()),
                ('content_vector', models.JSONField()),
                ('hybrid_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'song_vectors',
            },
        ),
    ]
