# Generated by Django 5.0.2 on 2025-05-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songvector',
            name='cf_vector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songvector',
            name='content_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
