# Generated by Django 5.0.2 on 2025-03-08 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(help_text="推荐算法方法，如 'hybrid'", max_length=50)),
                ('results', models.TextField(help_text='推荐结果的 JSON 格式字符串')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='计算时间')),
                ('user', models.ForeignKey(help_text='计算推荐结果的用户', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
